channels:
  - huggingface
  - pytorch
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - joblib
  - transformers>=3.1
  - sentence-transformers
  - ipykernel
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - pylint
  - black
  - pip:
    - omegaconf